name: workflow1
on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repos
        uses: actions/checkout@v4
      - name: install pyhon
        uses: actions/setup-node@v4
      - name: version details
        run: python -v
 
