name: workflow1
on: [psuh]
 branches: main

jobs:
  build and test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repos
        usese: actions/checkout@v4
      - name: install pyhon
        uses: actions/setup-node@v4
      - name: install dependencies
        run: npm install
 
